# Generated by Django 6.1 on 2026-08-25 20:41

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_id', models.UUIDField(db_index=True)),
                ('experiencia_id', models.UUIDField(db_index=True)),
                ('organizador_id', models.UUIDField(db_index=True)),
                ('codigo_ticket', models.CharField(db_index=True, max_length=12, unique=True)),
                ('cantidad_cupos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_reembolsado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('CHECK_IN', 'Check-in realizado'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada'), ('NO_ASISTIO', 'No asistio')], db_index=True, default='PENDIENTE_PAGO', max_length=20)),
                ('vence_en', models.DateTimeField(blank=True, null=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('check_in_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('origen_cancelacion', models.CharField(blank=True, choices=[('USUARIO', 'Usuario'), ('ORGANIZADOR', 'Organizador'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'reservas_reserva',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario_id', 'estado'], name='reserva_usuario_estado_idx'), models.Index(fields=['experiencia_id', 'estado'], name='reserva_exp_estado_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_cupos__gte', 1)), name='reserva_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('monto_total__gte', 0)), name='reserva_monto_no_negativo'), models.CheckConstraint(condition=models.Q(('monto_reembolsado__lte', models.F('monto_total'))), name='reserva_reembolso_acotado')],
            },
        ),
    ]
