# Generated by Django 6.1 on 2026-08-25 20:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('tipo_perfil', models.CharField(choices=[('ASISTENTE', 'Asistente'), ('ORGANIZADOR', 'Organizador')], default='ASISTENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'identidad_usuario',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('estado_verificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=64)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to='identidad.usuario')),
            ],
            options={
                'db_table': 'identidad_organizador',
            },
        ),
        migrations.CreateModel(
            name='InteresUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria_id', models.UUIDField(db_index=True)),
                ('nivel_afinidad', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses', to='identidad.usuario')),
            ],
            options={
                'db_table': 'identidad_interes_usuario',
                'ordering': ['-nivel_afinidad'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'categoria_id'), name='interes_unico_por_usuario'), models.CheckConstraint(condition=models.Q(('nivel_afinidad__gte', 1), ('nivel_afinidad__lte', 5)), name='interes_nivel_en_rango')],
            },
        ),
    ]
