# Generated by Django 6.1 on 2026-08-25 20:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInteres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria de interes',
                'verbose_name_plural': 'categorias de interes',
                'db_table': 'catalogo_categoria_interes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('aforo_maximo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'catalogo_ubicacion',
                'ordering': ['ciudad', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('aforo_maximo__gte', 1)), name='ubicacion_aforo_positivo')],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizador_id', models.UUIDField(db_index=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, max_length=2000)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDA', 'Hibrida')], default='PRESENCIAL', max_length=20)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(15)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cupo_maximo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cupo_disponible', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('AGOTADA', 'Agotada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], db_index=True, default='BORRADOR', max_length=20)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('categorias', models.ManyToManyField(blank=True, related_name='experiencias', to='catalogo.categoriainteres')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiencias', to='catalogo.ubicacion')),
            ],
            options={
                'db_table': 'catalogo_experiencia',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['estado', 'fecha_hora'], name='exp_estado_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cupo_disponible__lte', models.F('cupo_maximo'))), name='experiencia_cupo_disponible_coherente'), models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='experiencia_precio_no_negativo')],
            },
        ),
    ]
