# Generated by Django 6.0.7 on 2026-08-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cupo_disponible', models.IntegerField()),
                ('estado', models.CharField(default='abierta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('cantidad_cupos', models.IntegerField(default=1)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.experiencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
